apiVersion: apps/v1
kind: Deployment
metadata:
  name: kadio-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kadio
  template:
    metadata:
      labels:
        app: kadio
    spec:
      containers:
      - name: kadio-studio
        image: krgaurav01/kubernates-flask:01
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kadio-flask-service
spec:
  selector:
    app: kadio
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
