name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t krgaurav01/devopsified:${{ github.sha }} .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push krgaurav01/devopsified:${{ github.sha }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|krgaurav01/devopsified:.*|krgaurav01/devopsified:${{ github.sha }}|g" deployment.yaml
      - name: Clean up Docker
        run: docker system prune -af

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            DEPLOY_DIR="/home/ubuntu/kadio"
            # Clone repo if it doesn't exist, else pull the latest changes
            if [ ! -d "$DEPLOY_DIR" ]; then
              git clone https://github.com/kripto-geek/kadio.git $DEPLOY_DIR
            else
              cd $DEPLOY_DIR && git pull origin main
            fi
            cd $DEPLOY_DIR
            # Update the deployment manifest with the new image tag (commit SHA)
            sed -i "s|krgaurav01/devopsified:.*|krgaurav01/devopsified:${{ github.sha }}|g" deployment.yaml
            # Apply the updated deployment manifest to your Kubernetes cluster
            kubectl apply -f deployment.yaml
